//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheas_Cealer.Consts {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AboutMultilangConst {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutMultilangConst() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sheas_Cealer.Consts.AboutMultilangConst", typeof(AboutMultilangConst).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Link copied ✅ 的本地化字符串。
        /// </summary>
        public static string _LinkCopiedSnackbarMsg {
            get {
                return ResourceManager.GetString("_LinkCopiedSnackbarMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Blog 的本地化字符串。
        /// </summary>
        public static string BlogAboutInfoTitle {
            get {
                return ResourceManager.GetString("BlogAboutInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About Me 的本地化字符串。
        /// </summary>
        public static string CenterAboutInfoTitle {
            get {
                return ResourceManager.GetString("CenterAboutInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contact Me 的本地化字符串。
        /// </summary>
        public static string ContactAboutInfoTitle {
            get {
                return ResourceManager.GetString("ContactAboutInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string CopyLinkButtonName {
            get {
                return ResourceManager.GetString("CopyLinkButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to copy the corresponding link 的本地化字符串。
        /// </summary>
        public static string CopyLinkButtonToolTip {
            get {
                return ResourceManager.GetString("CopyLinkButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Space Time 的本地化字符串。
        /// </summary>
        public static string DeveloperAboutInfoContent {
            get {
                return ResourceManager.GetString("DeveloperAboutInfoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Developer 的本地化字符串。
        /// </summary>
        public static string DeveloperAboutInfoTitle {
            get {
                return ResourceManager.GetString("DeveloperAboutInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Usage Docs 的本地化字符串。
        /// </summary>
        public static string DocsAboutInfoTitle {
            get {
                return ResourceManager.GetString("DocsAboutInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License Agreement 的本地化字符串。
        /// </summary>
        public static string EulaAboutInfoTitle {
            get {
                return ResourceManager.GetString("EulaAboutInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string GotoLinkButtonName {
            get {
                return ResourceManager.GetString("GotoLinkButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to open the corresponding link 的本地化字符串。
        /// </summary>
        public static string GotoLinkButtonToolTip {
            get {
                return ResourceManager.GetString("GotoLinkButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Issue Feedback 的本地化字符串。
        /// </summary>
        public static string IssueAboutInfoTitle {
            get {
                return ResourceManager.GetString("IssueAboutInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Privacy Policy 的本地化字符串。
        /// </summary>
        public static string PolicyAboutInfoTitle {
            get {
                return ResourceManager.GetString("PolicyAboutInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Github Repo 的本地化字符串。
        /// </summary>
        public static string RepoAboutInfoTitle {
            get {
                return ResourceManager.GetString("RepoAboutInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        public static string VersionAboutInfoTitle {
            get {
                return ResourceManager.GetString("VersionAboutInfoTitle", resourceCulture);
            }
        }
    }
}
