//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheas_Cealer.Consts {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalMultilangConst {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalMultilangConst() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sheas_Cealer.Consts.GlobalMultilangConst", typeof(GlobalMultilangConst).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Elevate 的本地化字符串。
        /// </summary>
        public static string _AdminPermissionRequiredSnackbarButtonContent {
            get {
                return ResourceManager.GetString("_AdminPermissionRequiredSnackbarButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insufficient permissions. Please run as admin ⛔ 的本地化字符串。
        /// </summary>
        public static string _AdminPermissionRequiredSnackbarMsg {
            get {
                return ResourceManager.GetString("_AdminPermissionRequiredSnackbarMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clash plugin missing. Please download the full version ⬇️ 的本地化字符串。
        /// </summary>
        public static string _ClashPluginRequiredSnackbarMsg {
            get {
                return ResourceManager.GetString("_ClashPluginRequiredSnackbarMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clash is launching. Please wait for it to complete ⏳ 的本地化字符串。
        /// </summary>
        public static string _ClashWaitingForInitingSnackbarMsg {
            get {
                return ResourceManager.GetString("_ClashWaitingForInitingSnackbarMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simplified Chinese 的本地化字符串。
        /// </summary>
        public static string _LangOptionChineseName {
            get {
                return ResourceManager.GetString("_LangOptionChineseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 American English 的本地化字符串。
        /// </summary>
        public static string _LangOptionEnglishName {
            get {
                return ResourceManager.GetString("_LangOptionEnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follow System 的本地化字符串。
        /// </summary>
        public static string _LangOptionInheritName {
            get {
                return ResourceManager.GetString("_LangOptionInheritName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lang is changing. Restart to view the new lang 🌐 的本地化字符串。
        /// </summary>
        public static string _LangOptionRestartToApplySnackbarMsg {
            get {
                return ResourceManager.GetString("_LangOptionRestartToApplySnackbarMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nginx plugin missing. Please download the full version ⬇️ 的本地化字符串。
        /// </summary>
        public static string _NginxPluginRequiredSnackbarMsg {
            get {
                return ResourceManager.GetString("_NginxPluginRequiredSnackbarMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nginx is launching. Please wait for it to complete ⏳ 的本地化字符串。
        /// </summary>
        public static string _NginxWaitingForInitingSnackbarMsg {
            get {
                return ResourceManager.GetString("_NginxWaitingForInitingSnackbarMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        public static string _PluginRequiredSnackbarButtonContent {
            get {
                return ResourceManager.GetString("_PluginRequiredSnackbarButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Triple Ice Cream 的本地化字符串。
        /// </summary>
        public static string _ThemeColorBlueName {
            get {
                return ResourceManager.GetString("_ThemeColorBlueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tetraploid Melon 的本地化字符串。
        /// </summary>
        public static string _ThemeColorGreenName {
            get {
                return ResourceManager.GetString("_ThemeColorGreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hexavalent Orange Juice 的本地化字符串。
        /// </summary>
        public static string _ThemeColorOrangeName {
            get {
                return ResourceManager.GetString("_ThemeColorOrangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A Strawberry Milk 的本地化字符串。
        /// </summary>
        public static string _ThemeColorRedName {
            get {
                return ResourceManager.GetString("_ThemeColorRedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flavor is changing. Restart to taste the new flavor 🍹 的本地化字符串。
        /// </summary>
        public static string _ThemeColorRestartToApplySnackbarMsg {
            get {
                return ResourceManager.GetString("_ThemeColorRestartToApplySnackbarMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dihydrate Citric Acid 的本地化字符串。
        /// </summary>
        public static string _ThemeColorYellowName {
            get {
                return ResourceManager.GetString("_ThemeColorYellowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark Theme 的本地化字符串。
        /// </summary>
        public static string _ThemeStateDarkName {
            get {
                return ResourceManager.GetString("_ThemeStateDarkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follow System 的本地化字符串。
        /// </summary>
        public static string _ThemeStateInheritName {
            get {
                return ResourceManager.GetString("_ThemeStateInheritName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light Theme 的本地化字符串。
        /// </summary>
        public static string _ThemeStateLightName {
            get {
                return ResourceManager.GetString("_ThemeStateLightName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string AboutFlyoutItemTitle {
            get {
                return ResourceManager.GetString("AboutFlyoutItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rules 的本地化字符串。
        /// </summary>
        public static string RulesFlyoutItemTitle {
            get {
                return ResourceManager.GetString("RulesFlyoutItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string SettingsFlyoutItemTitle {
            get {
                return ResourceManager.GetString("SettingsFlyoutItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tools 的本地化字符串。
        /// </summary>
        public static string ToolFlyoutItemTitle {
            get {
                return ResourceManager.GetString("ToolFlyoutItemTitle", resourceCulture);
            }
        }
    }
}
