//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheas_Cealer.Consts {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainMultilangConst {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainMultilangConst() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sheas_Cealer.Consts.MainMultilangConst", typeof(MainMultilangConst).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Browser 的本地化字符串。
        /// </summary>
        public static string _BrowserPathDialogFilterFileType {
            get {
                return ResourceManager.GetString("_BrowserPathDialogFilterFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All processes of the selected browser will be closed before launching. Do you want to continue? 的本地化字符串。
        /// </summary>
        public static string _BrowserProcessKillPrompt {
            get {
                return ResourceManager.GetString("_BrowserProcessKillPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Some cealing hosts contain syntax errors and cannot be recognized. Do you want to continue anyway? 的本地化字符串。
        /// </summary>
        public static string _CealHostInvalidMsg {
            get {
                return ResourceManager.GetString("_CealHostInvalidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The clash conf contains syntax errors and cannot be recognized. Do you want to continue anyway? 的本地化字符串。
        /// </summary>
        public static string _ClashConfInvalidMsg {
            get {
                return ResourceManager.GetString("_ClashConfInvalidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clash failed to launch 的本地化字符串。
        /// </summary>
        public static string _ClashLaunchErrorMsg {
            get {
                return ResourceManager.GetString("_ClashLaunchErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I know you would click me, but nothing will actually happen. Whee~ 的本地化字符串。
        /// </summary>
        public static string _GameClickOnceMsg {
            get {
                return ResourceManager.GetString("_GameClickOnceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ugh, what are you doing. Please stop, I don&apos;t want to hurt anyone. Stop please, this is your last chance. Ugh, I can&apos;t control it anymore 的本地化字符串。
        /// </summary>
        public static string _GameClickThreeMsg {
            get {
                return ResourceManager.GetString("_GameClickThreeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No no no, don&apos;t click me. Sorry, I shouldn&apos;t have lied to you, I am a cursed button, and continuing to click me will bring disaster to the entire Sheas Cealer. Please believe me. This is not a game, and there are no new features here. Listen to me and use the normal functions. Please 的本地化字符串。
        /// </summary>
        public static string _GameClickTwiceMsg {
            get {
                return ResourceManager.GetString("_GameClickTwiceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You defeated the evil button and saved Sheas Cealer. You are the HERO! 的本地化字符串。
        /// </summary>
        public static string _GameEndingMsg {
            get {
                return ResourceManager.GetString("_GameEndingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Button Remaining HP. 的本地化字符串。
        /// </summary>
        public static string _GameGradeMsg {
            get {
                return ResourceManager.GetString("_GameGradeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It&apos;s dead. You&apos;re the HERO of Sheas Cealer 的本地化字符串。
        /// </summary>
        public static string _GameReviewEndingMsg {
            get {
                return ResourceManager.GetString("_GameReviewEndingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No, please kill me. I... can&apos;t control it... 的本地化字符串。
        /// </summary>
        public static string _GameStartMsg {
            get {
                return ResourceManager.GetString("_GameStartMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The nginx conf contains syntax errors and cannot be recognized. Do you want to continue anyway? 的本地化字符串。
        /// </summary>
        public static string _NginxConfInvalidMsg {
            get {
                return ResourceManager.GetString("_NginxConfInvalidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The local port 80 is occupied. Do you want to use port {0} to continue? This may cause the http connection to fail to automatically jump to https 的本地化字符串。
        /// </summary>
        public static string _NginxHttpPortOccupiedMsg {
            get {
                return ResourceManager.GetString("_NginxHttpPortOccupiedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The local port 443 is occupied. Do you want to use port {0} to continue? This may cause the global cealing to not work properly 的本地化字符串。
        /// </summary>
        public static string _NginxHttpsPortOccupiedMsg {
            get {
                return ResourceManager.GetString("_NginxHttpsPortOccupiedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nginx failed to launch. Do you want to open the error log? 的本地化字符串。
        /// </summary>
        public static string _NginxLaunchErrorPrompt {
            get {
                return ResourceManager.GetString("_NginxLaunchErrorPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning: The proxy core is under attack and failes to conceal SNI. The SNI removal mode has been turned on urgently. Do you want to continue? 的本地化字符串。
        /// </summary>
        public static string _NginxLaunchFlashingPrompt {
            get {
                return ResourceManager.GetString("_NginxLaunchFlashingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is an update available. Do you want to update upstream host? If No it will only open the upstream host web page for you 的本地化字符串。
        /// </summary>
        public static string _OverrideUpstreamHostPrompt {
            get {
                return ResourceManager.GetString("_OverrideUpstreamHostPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please remember to come back and stop the proxy manually after use. Do you want to continue? 的本地化字符串。
        /// </summary>
        public static string _ProxyLaunchPrompt {
            get {
                return ResourceManager.GetString("_ProxyLaunchPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update successfully 的本地化字符串。
        /// </summary>
        public static string _UpdateUpstreamHostSuccessMsg {
            get {
                return ResourceManager.GetString("_UpdateUpstreamHostSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upstream host is already up to date 的本地化字符串。
        /// </summary>
        public static string _UpstreamHostUtdMsg {
            get {
                return ResourceManager.GetString("_UpstreamHostUtdMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About Me 的本地化字符串。
        /// </summary>
        public static string AboutButtonContent {
            get {
                return ResourceManager.GetString("AboutButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to open the about window 的本地化字符串。
        /// </summary>
        public static string AboutButtonToolTip {
            get {
                return ResourceManager.GetString("AboutButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browser Cealing 的本地化字符串。
        /// </summary>
        public static string BrowserBarTextBlockText {
            get {
                return ResourceManager.GetString("BrowserBarTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Injecting startup args to conceal SNI extensions of the selected browser&apos;s traffic. Browsers with Chromium version 141.0.7356.0 or above are not supported. Rules beginning with $ or ^ are ignored 的本地化字符串。
        /// </summary>
        public static string BrowserBarTextBlockToolTip {
            get {
                return ResourceManager.GetString("BrowserBarTextBlockToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Cealing 的本地化字符串。
        /// </summary>
        public static string BrowserButtonContent {
            get {
                return ResourceManager.GetString("BrowserButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to launch the injected browser 的本地化字符串。
        /// </summary>
        public static string BrowserButtonToolTip {
            get {
                return ResourceManager.GetString("BrowserButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cealer 的本地化字符串。
        /// </summary>
        public static string CealerLabelText {
            get {
                return ResourceManager.GetString("CealerLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global Purging 的本地化字符串。
        /// </summary>
        public static string ClashBarTextBlockText {
            get {
                return ResourceManager.GetString("ClashBarTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Clash TUN + DoH to resolve DNS queries of system-wide traffic against DNS pollution. Cealing host is not used in this feature 的本地化字符串。
        /// </summary>
        public static string ClashBarTextBlockToolTip {
            get {
                return ResourceManager.GetString("ClashBarTextBlockToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GLB. Purging INIT. 的本地化字符串。
        /// </summary>
        public static string ClashButtonIsInitingContent {
            get {
                return ResourceManager.GetString("ClashButtonIsInitingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop GLB. Purging 的本地化字符串。
        /// </summary>
        public static string ClashButtonIsRunningContent {
            get {
                return ResourceManager.GetString("ClashButtonIsRunningContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to stop the local Clash 的本地化字符串。
        /// </summary>
        public static string ClashButtonIsRunningToolTip {
            get {
                return ResourceManager.GetString("ClashButtonIsRunningToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start GLB. Purging 的本地化字符串。
        /// </summary>
        public static string ClashButtonIsStoppedContent {
            get {
                return ResourceManager.GetString("ClashButtonIsStoppedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to launch a local Clash 的本地化字符串。
        /// </summary>
        public static string ClashButtonIsStoppedToolTip {
            get {
                return ResourceManager.GetString("ClashButtonIsStoppedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GLB. Purging STP. 的本地化字符串。
        /// </summary>
        public static string ClashButtonIsStoppingContent {
            get {
                return ResourceManager.GetString("ClashButtonIsStoppingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GLB. Purging CHA. 的本地化字符串。
        /// </summary>
        public static string CoclashButtonIsInitingContent {
            get {
                return ResourceManager.GetString("CoclashButtonIsInitingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GLB. Cealing INIT. 的本地化字符串。
        /// </summary>
        public static string ConginxButtonIsInitingContent {
            get {
                return ResourceManager.GetString("ConginxButtonIsInitingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Elevate 的本地化字符串。
        /// </summary>
        public static string ElevateButtonName {
            get {
                return ResourceManager.GetString("ElevateButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to restart as admin 的本地化字符串。
        /// </summary>
        public static string ElevateButtonToolTip {
            get {
                return ResourceManager.GetString("ElevateButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to expand extention bar 的本地化字符串。
        /// </summary>
        public static string ExpandToggleButtonClosedToolTip {
            get {
                return ResourceManager.GetString("ExpandToggleButtonClosedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expand 的本地化字符串。
        /// </summary>
        public static string ExpandToggleButtonName {
            get {
                return ResourceManager.GetString("ExpandToggleButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to collapse extention bar 的本地化字符串。
        /// </summary>
        public static string ExpandToggleButtonOpenToolTip {
            get {
                return ResourceManager.GetString("ExpandToggleButtonOpenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Github 的本地化字符串。
        /// </summary>
        public static string GithubButtonName {
            get {
                return ResourceManager.GetString("GithubButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to open my github repo 的本地化字符串。
        /// </summary>
        public static string GithubButtonToolTip {
            get {
                return ResourceManager.GetString("GithubButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to open navigation drawer 的本地化字符串。
        /// </summary>
        public static string HumburgerToggleButtonClosedToolTip {
            get {
                return ResourceManager.GetString("HumburgerToggleButtonClosedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Navigation 的本地化字符串。
        /// </summary>
        public static string HumburgerToggleButtonName {
            get {
                return ResourceManager.GetString("HumburgerToggleButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to close navigation drawer 的本地化字符串。
        /// </summary>
        public static string HumburgerToggleButtonOpenToolTip {
            get {
                return ResourceManager.GetString("HumburgerToggleButtonOpenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to stop global cealing 的本地化字符串。
        /// </summary>
        public static string LaunchButtonActiveToolTip {
            get {
                return ResourceManager.GetString("LaunchButtonActiveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to start global cealing 的本地化字符串。
        /// </summary>
        public static string LaunchButtonInactiveToolTip {
            get {
                return ResourceManager.GetString("LaunchButtonInactiveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch 的本地化字符串。
        /// </summary>
        public static string LaunchButtonName {
            get {
                return ResourceManager.GetString("LaunchButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global Cealing 的本地化字符串。
        /// </summary>
        public static string NginxBarTextBlockText {
            get {
                return ResourceManager.GetString("NginxBarTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Nginx local reverse proxy to conceal SNI extensions of system-wide traffic. Fragment is not supported. Wildcards not at the beginning of the rules are ignored. Rules beginning with # % or ^ are ignored 的本地化字符串。
        /// </summary>
        public static string NginxBarTextBlockToolTip {
            get {
                return ResourceManager.GetString("NginxBarTextBlockToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GLB. Cealing INIT. 的本地化字符串。
        /// </summary>
        public static string NginxButtonIsInitingContent {
            get {
                return ResourceManager.GetString("NginxButtonIsInitingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop GLB. Cealing 的本地化字符串。
        /// </summary>
        public static string NginxButtonIsRunningContent {
            get {
                return ResourceManager.GetString("NginxButtonIsRunningContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to stop the local Nginx 的本地化字符串。
        /// </summary>
        public static string NginxButtonIsRunningToolTip {
            get {
                return ResourceManager.GetString("NginxButtonIsRunningToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start GLB. Cealing 的本地化字符串。
        /// </summary>
        public static string NginxButtonIsStoppedContent {
            get {
                return ResourceManager.GetString("NginxButtonIsStoppedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to launch a local Nginx 的本地化字符串。
        /// </summary>
        public static string NginxButtonIsStoppedToolTip {
            get {
                return ResourceManager.GetString("NginxButtonIsStoppedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click Now 的本地化字符串。
        /// </summary>
        public static string NoClickButtonIsFlashingContent {
            get {
                return ResourceManager.GetString("NoClickButtonIsFlashingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click this button now 的本地化字符串。
        /// </summary>
        public static string NoClickButtonIsFlashingToolTip {
            get {
                return ResourceManager.GetString("NoClickButtonIsFlashingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Clicking 的本地化字符串。
        /// </summary>
        public static string NoClickButtonIsStoppedContent {
            get {
                return ResourceManager.GetString("NoClickButtonIsStoppedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not click this button 的本地化字符串。
        /// </summary>
        public static string NoClickButtonIsStoppedToolTip {
            get {
                return ResourceManager.GetString("NoClickButtonIsStoppedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More 的本地化字符串。
        /// </summary>
        public static string OverflowPopupBoxName {
            get {
                return ResourceManager.GetString("OverflowPopupBoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to open more options 的本地化字符串。
        /// </summary>
        public static string OverflowPopupBoxToolTip {
            get {
                return ResourceManager.GetString("OverflowPopupBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pin 的本地化字符串。
        /// </summary>
        public static string PinButtonName {
            get {
                return ResourceManager.GetString("PinButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to pin extention bar 的本地化字符串。
        /// </summary>
        public static string PinButtonToolTip {
            get {
                return ResourceManager.GetString("PinButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill in a Chromium-based browser path 的本地化字符串。
        /// </summary>
        public static string SettingsBoxBrowserPathToolTip {
            get {
                return ResourceManager.GetString("SettingsBoxBrowserPathToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill in extra Chromium startup args 的本地化字符串。
        /// </summary>
        public static string SettingsBoxExtraArgsToolTip {
            get {
                return ResourceManager.GetString("SettingsBoxExtraArgsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill in an upstream host URL 的本地化字符串。
        /// </summary>
        public static string SettingsBoxUpstreamUrlToolTip {
            get {
                return ResourceManager.GetString("SettingsBoxUpstreamUrlToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Appearance Settings 的本地化字符串。
        /// </summary>
        public static string SettingsButtonContent {
            get {
                return ResourceManager.GetString("SettingsButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to open the settings window 的本地化字符串。
        /// </summary>
        public static string SettingsButtonToolTip {
            get {
                return ResourceManager.GetString("SettingsButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse Path 的本地化字符串。
        /// </summary>
        public static string SettingsFunctionButtonBrowserPathContent {
            get {
                return ResourceManager.GetString("SettingsFunctionButtonBrowserPathContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Args 的本地化字符串。
        /// </summary>
        public static string SettingsFunctionButtonExtraArgsContent {
            get {
                return ResourceManager.GetString("SettingsFunctionButtonExtraArgsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to process settings 的本地化字符串。
        /// </summary>
        public static string SettingsFunctionButtonToolTip {
            get {
                return ResourceManager.GetString("SettingsFunctionButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset URL 的本地化字符串。
        /// </summary>
        public static string SettingsFunctionButtonUpstreamUrlContent {
            get {
                return ResourceManager.GetString("SettingsFunctionButtonUpstreamUrlContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browser Path 的本地化字符串。
        /// </summary>
        public static string SettingsStateButtonBrowserPathContent {
            get {
                return ResourceManager.GetString("SettingsStateButtonBrowserPathContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extra Args 的本地化字符串。
        /// </summary>
        public static string SettingsStateButtonExtraArgsContent {
            get {
                return ResourceManager.GetString("SettingsStateButtonExtraArgsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to switch settings 的本地化字符串。
        /// </summary>
        public static string SettingsStateButtonToolTip {
            get {
                return ResourceManager.GetString("SettingsStateButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upstream URL 的本地化字符串。
        /// </summary>
        public static string SettingsStateButtonUpstreamUrlContent {
            get {
                return ResourceManager.GetString("SettingsStateButtonUpstreamUrlContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sheas 的本地化字符串。
        /// </summary>
        public static string SheasLabelText {
            get {
                return ResourceManager.GetString("SheasLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sheas Cealer 的本地化字符串。
        /// </summary>
        public static string TitleTextBlockText {
            get {
                return ResourceManager.GetString("TitleTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Host For Update 的本地化字符串。
        /// </summary>
        public static string UpdateHostButtonContent {
            get {
                return ResourceManager.GetString("UpdateHostButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tap to check host for update 的本地化字符串。
        /// </summary>
        public static string UpdateHostButtonToolTip {
            get {
                return ResourceManager.GetString("UpdateHostButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Software For Update 的本地化字符串。
        /// </summary>
        public static string UpdateSoftwareButtonContent {
            get {
                return ResourceManager.GetString("UpdateSoftwareButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tap to check software for update 的本地化字符串。
        /// </summary>
        public static string UpdateSoftwareButtonToolTip {
            get {
                return ResourceManager.GetString("UpdateSoftwareButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Upstream Host 的本地化字符串。
        /// </summary>
        public static string UpdateUpstreamHostButtonContent {
            get {
                return ResourceManager.GetString("UpdateUpstreamHostButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to update upstream host 的本地化字符串。
        /// </summary>
        public static string UpdateUpstreamHostButtonToolTip {
            get {
                return ResourceManager.GetString("UpdateUpstreamHostButtonToolTip", resourceCulture);
            }
        }
    }
}
